### ISSUE TITLE
Problema nel calcolo dell'accuratezza

### ISSUE THREAD

**Issue by LeoGori** [frallebini/decision-tree-learning#1]
Salve,
avrei una domanda relativa al progetto, poichè non riesco a trovare altre informazioni sull'algoritmo del rule post-pruning. Ho notato che il metodo predict(self, example) della classe set_of_rules.py, usato per calcolare l'accuratezza del set di regole sul validation set, restituisce la prima regola del set che soddisfa i vincoli degli attributi dell'esempio, e successivamente confronta la predizione della regola con quella dell'esempio. Ho pensato che nell'eventualità che la predizione della regola restituita non corrispondesse alla classificazione dell'esempio, potrebbe comunque esistere una regola all'interno del set di regole che soddisfi i vincoli dello stesso esempio e che lo predica correttamente, ma non viene considerato. Di conseguenza il calcolo dell'accuratezza potrebbe essere sbagliato. Ho aperto questo issue principalmente per sapere se c'è un motivo per cui hai implementato il codice in questo modo oppure se è un errore.

**Comment by francescoballerini** [comment]
Hi, it's been more than a year since I wrote this code; I uploaded here with no intention of maintaining it, but just because I thought that someone might find it useful and build on top of it. To answer to your question, I do not remember exactly the reasoning behind my implementation choices, but what I can tell you is that I recall that the experimental results I was getting with the rule-pruning version were not really that much better than those given by the standard implementation, so you might be right. Feel free to update the code in case your strategy turns out to be more successful than mine!

**Comment by frallebini** [comment]
Hi,

Your observation is based on the assumption that, given an example, there might be more than one rule corresponding to that example. However, I think you're wrong, and here's why:

1.  **For each example, there is only one path from the root to a leaf in the decision tree corresponding to that example.**
_Proof._  Let `e` be an example and let `t` be the decision tree. For each node (i.e. attribute test) in the tree, starting from the root, choose the branch corresponding to the value of that attribute in `e`, until you reach a leaf `l` (i.e. a value of the target attribute).  By doing so, you get a path from the root to `l` in `t` corresponding to `e`. Being `t` a tree, such path is unique.

2.  **For each path from the root to a leaf in the decision tree, there is only one rule corresponding to that path.**
_Proof._ By construction of the rules themselves.

If you concatenate 1 and 2, you get that, **for each example, there is only one rule corresponding to that example**, which negates your assumption.
